package com.example.testingspecification.review;

import com.example.testingspecification.book.Book;
import com.example.testingspecification.song.Song;
import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import lombok.extern.slf4j.Slf4j;

/**
 * Entity representing a review of a book.
 */
@Slf4j
@Entity
@Table
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Getter
@Setter
@Builder
public class Review {

    /**
     * The unique identifier for the review.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * The book that this review is associated with.
     * Mapped with a foreign key to the Book entity.
     * This field cannot be null.
     */
    @ManyToOne
    @JoinColumn(name = "book_id", nullable = false)
    private Book book;
    private String text;
    private int rating;
    private LocalDate date;
    private String reviewerName;
    @ManyToOne
    @JoinColumn(name = "song_id")
    private Song song;
    //    @ManyToOne
    //    @JoinColumn(name = "album_id")
    //    private Album album;
    /**
     * Constructs a new {@code Review} with the specified details.
     *
     * @param id            the unique identifier for the review
     * @param book          the book that this review is associated with
     * @param text          the text content of the review
     * @param rating        the rating given in the review
     * @param date          the date when the review was written
     * @param reviewerName  the name of the person who wrote the review
     */

    public Review(long id, Book book, String text, int rating, LocalDate date, String reviewerName) {
        this.id = id;
        this.book = book;
        this.text = text;
        this.rating = rating;
        this.date = date;
        this.reviewerName = reviewerName;
        log.info("Review created");
    }

}

